name: Health Check

# on:
#   schedule:
#     - cron: '0 * * * *'

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: ping URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://fullstackopen-part11.herokuapp.com/
